name: app_python

on:
  push:
    branches:
      - main  # Adjust this to your main branch name
      - lab3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Replace with your desired Python version

    - name: Cache Dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('app_python/**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Dependencies
      run: pip install -r app_python/requirements.txt

    - name: Lint Code
      run: pre-commit run --all-files

    - name: Run Tests
      run: python app_python/manage.py test

    - name: Install Snyk CLI
      run: npm install -g snyk

    - name: Run Snyk to check for vulnerabilities
      run: snyk test --file=app_python/requirements.txt
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    - name: Docker Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        cd app_python
        docker build -t my-cool-django-app .
        docker tag my-cool-django-app:latest rametago/my-first-repo:latest
        docker push rametago/my-first-repo:latest

# Add more steps as needed
